; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mega

[env]
extra_scripts = pre:tools/inject_version.py

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/domnulvlad/KLineKWP1281Lib.git
    MCUFRIEND_kbv
    Adafruit GFX Library
    Adafruit BusIO
build_flags =
    -Wall -Wextra -Wpedantic -Wunused -Wshadow -Wformat=2
    -Wno-unused-parameter
    -fno-exceptions
    -fno-threadsafe-statics
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

[env:mega_debug]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    ${env:mega.lib_deps}
build_flags =
    ${env:mega.build_flags}
    -D OBD_DEBUG
